### ISSUE TITLE
Reblock process crashing

### ISSUE THREAD

**Issue by Douglas-K** [linz/lds_topo_reblocker#14]
Reblock process crashed when running LayerReader.py on a local copy of polygon shapefiles.

Crashed on waterfall_poly, then tried removing that shapefile, but crashed on dry_dock_poly next.

![image](https://user-images.githubusercontent.com/12453560/84096601-6f556c00-aa56-11ea-8c46-5eea529ff7ed.png)

Checked the DB on prdassgeo02, and it appears the tables and sequences for both features were existing before running Reblocker, but they have since disappeared!  May need to roll back / get backups for these?

This was attempted from LINZ-Corp in the Wlg office by @Douglas-K .  Shannon McColley tried to run the Reblocker prior to this from home via VPN but the VPN times out for her, losing connection to Reblocker.  I wonder if this caused issues to the DB?

**Comment by josephramsay** [comment]
Can confirm that _waterfall_poly_ and _dry_dock_poly_ are missing but their edited versions _new_waterfall_poly_ and _new_drydock_poly_ are still available. One quick fix might be to copy _new__ to _\<missing\>_ and lose some history. I can't recommend this however, until we at least understand why the original tables are missing. Will test Friday when access to geoservers restored

**Comment by josephramsay** [comment]
Looks like the copy function used to load a shapefile isn't working as it used to. What would normally happen is a new layer gets created using datasource.CopyLayer(...) and then we attempt to modify the SRID. Because the new layer hasn't been created the SRID command fails

**Comment by josephramsay** [comment]
Investigating this it seems the gdal CopyLayer function is behaving differently. When copying a layer CopyLayer creates a new layer with a name matching the input source and attempts to set the ogc_fid to zero. This however won't work in a sequence that starts at 1. Pre creating (and incrementing) a duplicate sequence fails when CopyLayer sees the existing sequence and creates another in parallel.
There doesn't seem to be a way to use CopyLayer and set a sequence start so when a failure is encountered we catch this and revert to a simple CreateLayer and populate by feature. Catching this error is also troublesome since OGR doesn't report errors back to the process, rather it posts some error text on stderr. In order to assess whether an error has occurred we check the shape and in memory layer post copy and check for differences. If there are any an exception is thrown.
The fallback to CreateLayer has also been set to overwrite so any in memory layers from the CopyLayer stage are overwritten.
@Douglas-K try swapping out this file https://github.com/linz/lds_topo_reblocker/blob/fix/shape-load-fail/src/LayerReader.py

**Comment by Douglas-K** [comment]
@josephramsay, we are mostly running this in Python 2 at the moment, so it is falling over at `from contextlib import redirect_stdout`.  Are you able to add a Python 2 alternative for that?

**Comment by josephramsay** [comment]
@Douglas-K Done, didn't actually need that import so just removed it

**Comment by Douglas-K** [comment]
@josephramsay that's good but getting this error now...
![image](https://user-images.githubusercontent.com/12453560/85234478-c6e5d580-b461-11ea-89d4-c5dffc4ba44e.png)

**Comment by josephramsay** [comment]
That should be the same error as above (and will keep appearing while testing). Can you confirm that the processing is working though? We should fall back to the slow write method and complete successfully.

**Comment by Douglas-K** [comment]
Oh yeah, so it is the same error!  In this case though, it is crashing on 'dry_dock_poly' and does not process.  Seems to be because the 'dry_dock_poly' table was removed when it crashed previously.  Is it easy enough to create a new table (based on the shapefile) if it doesn't already exist?
I tested on another feature that has an existing table and the process works well with no error reported.

**Comment by josephramsay** [comment]
Interesting, waterfalls was succeeding while dry_dock wasn't because of the comparison between SRIDs which are already in the correct format for dry_dock. When the comparison between original and (faulty) copied layers is done waterfall was failing and falling back but dry_dock wasn't so the backup didn't get attempted.... Too much info sorry :| Anyway, try again now.

**Comment by Douglas-K** [comment]
Just realised that when I ran the script the last couple of times to test, I was using the code from Master rather than your Branch so that didn't help!  Having other issues now...

`from abc import ABC` doesn't work.  Maybe need an ABCMeta alternative for Python 2?

Then it crashes further along too...
![image](https://user-images.githubusercontent.com/12453560/85455336-e875c700-b5f1-11ea-8202-27946e5a607f.png)

**Comment by josephramsay** [comment]
Found a hack for ABCs which only requires an import change. While I was messing with imports I swapped out a 2-3 version check to pick urllib imports in favour of six which should work better. Tested and working on py3 but you'll have to let me know for py2.  :crossed_fingers:

**Comment by josephramsay** [comment]
Wrote fallback to per-feature copy (wrapped in gdal error extractor) which still failed to transfer macrons. Setting preferences on a layer/datasource and driver basis seems to be working now though. Credit @billgeo for the pointer

**Comment by josephramsay** [comment]
Addressed with https://github.com/linz/lds_topo_reblocker/commit/1fb1c553b3c85ff57243a14d9b47b95c437c424f

**Comment by josephramsay** [comment]
@Douglas-K just closing this since you don't seem to be having any more issues. Please reopen if needed

**Comment by Douglas-K** [comment]
Thanks @josephramsay, seems to work well for Shannon on Windows 10 Python 3.  I had forgotten to close.
